wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: testo12345

wordpress:
  image: legendary/wordpress-nginx:testing2
  links:
    - wordpress_db:mysql
  ports:
    - 38550:80
  environment:
      - VIRTUAL_HOST=test3.node001.legendary-server.de
      - LETSENCRYPT_HOST=test3.node001.legendary-server.de
      - LETSENCRYPT_EMAIL=nordloh.kevin@gmail.com
